### ISSUE TITLE
missing input files

### ISSUE THREAD

**Issue by mycode-bit** [churchlab/Deep_diversification_AAV#1]
Hello,
I am new here. 
I am interested in your approach for AAV, and tried to run the code, but find out that many input files were missing.
Could you share your input file here?

Thanks

**Comment by mycode-bit** [comment]
like barcodes16-1.txt,  chip1_GAS_nredundant.csv etc were not there.

**Comment by samsinai** [comment]
I have now added a [dropbox link](https://www.dropbox.com/sh/lmd8wmgibz24r2h/AABnfUHq6k-H_sT7I0UGR_D5a?dl=0) in the readme with those files.
