### ISSUE TITLE
AttributeError: 'Oligo' object has no attribute 'set_homopolymer'

### ISSUE THREAD

**Issue by 0xlength** [churchlab/Deep_diversification_AAV#2]
excuse me~

I'am a researcher from chinese.

i got some error from your code, it seen like someone forget some code 

Path: "Deep_diversification_AAV / Synthesis_pipeline / src / oligo.py " --> has  not attribute or functions of set_homopolymer()

errorr running file path:  "Deep_diversification_AAV / Synthesis_pipeline / Step1_AAV2_chip_synthesis.ipynb"

the has some code about that error file:

> oligo_obj=Oligo(debug=False)
> oligo_obj.set_restriction_enzymes_to_avoid([x.site for x in [HindIII, XbaI,BsrBI,BsmBI]])
> oligo_obj.set_targeted_restriction_enzymes([x.site for x in [BbsI, BsaI, EcoRV]])
> oligo_obj.set_homopolymer(homopolymer)

waiting for your reply

**Comment by EricLeng1101** [comment]
> excuse me~
> 
> I'am a researcher from chinese.
> 
> i got some error from your code, it seen like someone forget some code
> 
> Path: "Deep_diversification_AAV / Synthesis_pipeline / src / oligo.py " --> has not attribute or functions of set_homopolymer()
> 
> errorr running file path: "Deep_diversification_AAV / Synthesis_pipeline / Step1_AAV2_chip_synthesis.ipynb"
> 
> the has some code about that error file:
> 
> > oligo_obj=Oligo(debug=False)
> > oligo_obj.set_restriction_enzymes_to_avoid([x.site for x in [HindIII, XbaI,BsrBI,BsmBI]])
> > oligo_obj.set_targeted_restriction_enzymes([x.site for x in [BbsI, BsaI, EcoRV]])
> > oligo_obj.set_homopolymer(homopolymer)
> 
> waiting for your reply
